MVC/Controllers/AgenciaController.cs
using MVC.Models.Entities;
using Newtonsoft.Json;
using Shared.Entities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MVC.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class AgenciaController : Controller
    {
        private readonly string Baseurl = ConfigurationManager.AppSettings["baseurl"];

        // GET: Agencia
        public async Task<ActionResult> Index()
        {
            List<Agencia> lista = new List<Agencia>();
            List<AgenciaModel> aux = new List<AgenciaModel>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                HttpResponseMessage Res = await client.GetAsync("api/agencia");

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    lista = JsonConvert.DeserializeObject<List<Agencia>>(EmpResponse);
                }
                foreach (Agencia ag in lista)
                {
                    if(ag.CodigoExterno == null)
                    {
                        aux.Add(new AgenciaModel()
                        {
                            Id = ag.Id,
                            Direccion = ag.Direccion,
                            Nombre = ag.Nombre,
                            EntregaDomicilio = ag.EntregaDomicilio
                        });
                    }
                }
                return View(aux);
            }
        }

        // GET: Agencia/Details/5
        public async Task<ActionResult> Details(int id)
        {
            using (var client = new HttpClient())
            {
                Agencia ag = null;
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                string apiuri = "api/agencia/" + id;
                HttpResponseMessage Res = await client.GetAsync(apiuri);

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    ag = JsonConvert.DeserializeObject<Agencia>(EmpResponse);
                }
                if (ag != null)
                {
                    return View(new AgenciaModel()
                    {
                        Id = ag.Id,
                        Nombre = ag.Nombre,
                        Direccion = ag.Direccion,
                        EntregaDomicilio = ag.EntregaDomicilio
                    });
                }
                return View("NotFound");
            }
        }

        // GET: Agencia/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Agencia/Create
        [HttpPost]
        public async Task<ActionResult> Create(AgenciaModel model)
        {
            try
            {
                string json =
                    "{" +
                      "'Nombre': '" + model.Nombre + "'," +
                      "'Direccion': '" + model.Direccion + "'," +
                      "'EntregaDomicilio': '" + model.EntregaDomicilio + "'" +
                    "}";
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                    string postUri = Baseurl + "api/agencia";
                    var response = await client.PostAsync(
                        postUri,
                        new StringContent(json, Encoding.UTF8, "application/json")
                    );
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Agencia/Edit/5
        [HttpGet]
        [Route("api/Agencia/Details/{id}")]
        public async Task<ActionResult> Edit(int id)
        {
            using (var client = new HttpClient())
            {
                Agencia ag = null;
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                string apiuri = "api/agencia/" + id;
                HttpResponseMessage Res = await client.GetAsync(apiuri);

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    ag = JsonConvert.DeserializeObject<Agencia>(EmpResponse);
                }
                if (ag != null)
                {
                    return View(new AgenciaModel()
                    {
                        Id = ag.Id,
                        Direccion = ag.Direccion,
                        Nombre = ag.Nombre,
                        EntregaDomicilio = ag.EntregaDomicilio
                    });
                }
                return View("NotFound");
            }
        }

        // POST: Agencia/Edit/5
        [HttpPost]
        [Route("api/Agencia/Edit/{id}")]
        public async Task<ActionResult> Edit(int id, AgenciaModel model)
        {
            try
            {
                string json =
                    "{" +
                      "'Id': " + id + "," +
                      "'Nombre': '" + model.Nombre + "'," +
                      "'Direccion': '" + model.Direccion + "'," +
                      "'EntregaDomicilio': '" + model.EntregaDomicilio + "'" +
                    "}";
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);

                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                    string editUri = Baseurl + "api/agencia/" + id;
                    var response = await client.PutAsync(
                        editUri,
                        new StringContent(json, Encoding.UTF8, "application/json")
                    );
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Agencia/Delete/5
        [HttpGet]
        [Route("api/Agencia/Details/{id}")]
        public async Task<ActionResult> Delete(int id)
        {
            using (var client = new HttpClient())
            {
                Agencia ag = null;
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                string apiuri = "api/agencia/" + id;
                HttpResponseMessage Res = await client.GetAsync(apiuri);

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    ag = JsonConvert.DeserializeObject<Agencia>(EmpResponse);
                }
                if (ag != null)
                {
                    return View(new AgenciaModel()
                    {
                        Id = ag.Id,
                        Direccion = ag.Direccion,
                        Nombre = ag.Nombre,
                        EntregaDomicilio = ag.EntregaDomicilio
                    });
                }
                return View("NotFound");
            }
        }

        // POST: Agencia/Delete/5
        [HttpPost]
        [Route("api/Agencia/Delete/{id}")]
        public async Task<ActionResult> Delete(int id, FormCollection collection)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl + "api/");

                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                    var response = await client.DeleteAsync("agencia/" + id.ToString());
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/Controllers/ReportePaquetesController.cs
using MVC.Models;
using MVC.Models.Entities;
using Newtonsoft.Json;
using Shared.Entities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MVC.Controllers
{
    [Authorize(Roles = "Funcionario")]
    public class ReportePaquetesController : Controller
    {
        private readonly string Baseurl = ConfigurationManager.AppSettings["baseurl"];

        private async Task<string> GetEstadoPaquete(int idPaq)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                string apiuri = "api/estadopaquete?id=" + idPaq;
                HttpResponseMessage Res = await client.GetAsync(apiuri);

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    return JsonConvert.DeserializeObject<String>(EmpResponse);
                }
                return "Error";
            }
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            List<Usuario> lista = new List<Usuario>();
            List<Usuario> aux = new List<Usuario>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                HttpResponseMessage Res = await client.GetAsync("api/clientes");

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    aux = JsonConvert.DeserializeObject<List<Usuario>>(EmpResponse);
                }
            }
            lista.Add(new Usuario() { 
                Id = 999,
                Nombre = "Ninguno"
            });
            lista.AddRange(aux);
            List<Usuario> aux2 = new List<Usuario>();
            foreach (Usuario usu in lista)
            {
                if(usu.CodigoExterno == null)
                {
                    aux2.Add(usu);
                }
            }

            ViewBag.Remitentes = aux2;
            ViewBag.Destinatarios = aux2;
            ViewBag.Estados = new string[6] {"Ninguno", "Recibido en origen", "Esperando en origen", "En viaje", "Recibido en Destino", "Entregado al Cliente" };
            var a = new ReportePaquetesModel();
            a.FechaDesde = DateTime.Now.AddMonths(-1);
            a.FechaHasta = DateTime.Now;
            return View(a);
        }

        [HttpPost]
        public async Task<ActionResult> Index(FormCollection collection)
        {
            List<Paquete> lista = new List<Paquete>();
            List<PaqueteModel> aux = new List<PaqueteModel>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                string estado = collection["Estado"];
                string estadobuenito= "";
                if(estado != "Ninguno")
                {
                    estadobuenito = estado;
                }
                string nuevaFechaD;
                string nuevaFechaH;
                if(collection["FechaDesde"] == null || collection["FechaDesde"] == "")
                {
                    nuevaFechaD = DateTime.Now.AddYears(14).Year + "-" + DateTime.Now.Month + "-" + DateTime.Now.Day;
                }
                else
                {
                    nuevaFechaD = collection["FechaDesde"];
                }
                if (collection["FechaHasta"] == null || collection["FechaHasta"] == "")
                {
                    nuevaFechaH = DateTime.Now.AddYears(14).Year + "-" + DateTime.Now.Month + "-" + DateTime.Now.Day;
                }
                else
                {
                    nuevaFechaH = collection["FechaHasta"];
                }
                string uri = "api/Paquete/Filtro?fechaDesde=" + nuevaFechaD + "&fechaHasta=" + nuevaFechaH + "&estado=" + estadobuenito + "&idDestinatario=" + collection["Destinatario"] + "&idRemitente=" + collection["Remitente"];
                HttpResponseMessage Res = await client.GetAsync(uri);

                if (Res.IsSuccessStatusCode)
                {
                    var EmpResponse = Res.Content.ReadAsStringAsync().Result;
                    lista = JsonConvert.DeserializeObject<List<Paquete>>(EmpResponse);
                }
                foreach (Paquete paq in lista)
                {
                    if(paq.CodigoExterno == null)
                    {
                        int HoraDeEntrega = 999;
                        using (var client2 = new HttpClient())
                        {

                            client2.BaseAddress = new Uri(Baseurl);

                            client2.DefaultRequestHeaders.Clear();
                            client2.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                            client2.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["token"].Value);

                            string apiuri2 = "api/paquete/GetHoraDeEntrega?id=" + paq.Id;
                            HttpResponseMessage Res2 = await client2.GetAsync(apiuri2);

                            if (Res2.IsSuccessStatusCode)
                            {
                                var EmpResponse2 = Res2.Content.ReadAsStringAsync().Result;
                                HoraDeEntrega = JsonConvert.DeserializeObject<int>(EmpResponse2);
                            }
                        }
                        string hde;
                        if (HoraDeEntrega == 999)
                        {
                            hde = "ERROR";
                        }
                        else if (HoraDeEntrega == -1)
                        {
                            hde = "(No tiene)";
                        }
                        else
                        {
                            hde = HoraDeEntrega.ToString();
                        }
                        aux.Add(new PaqueteModel()
                        {
                            Id = paq.Id,
                            Descripcion = paq.Descripcion,
                            FechaEntrega = paq.FechaEntrega,
                            FechaIngreso = paq.FechaIngreso,
                            Remitente = paq.Remitente,
                            Destinatario = paq.Destinatario,
                            Estado = await GetEstadoPaquete(paq.Id),
                            HoraDeEntrega = hde
                        });
                    }
                }
            }

            return View("GetReportePaquetes", aux);
        }

        [HttpGet]
        [Route("api/Paquete/GetReportePaquetes/")]
        public ActionResult GetReportePaquetes(IEnumerable<PaqueteModel> paquetes)
        {
            return View(paquetes);
        }
    }
}

MVC/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Recurso no encontrado";
}

<h2>Recurso no encontrado</h2>

<div>
    <br />
    <h5>Lo sentimos, no hemos encontrado el recurso que solicitas</h5>
</div>

MVC/Views/Shared/Unauthorized.cshtml
@{
    ViewBag.Title = "Error";
}

<h2>Acceso denegado</h2>

<div>
    <br />
    <h5>Lo sentimos, usted no tiene los permisos necesarios para acceder a este recurso.</h5>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TrackingFULL</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top sidebar-navbar-inverse">
        <a href="@Url.Action("Index", "Home")" class="navbar-brand">
            <img src="~/Img/logo.png" />
        </a>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (!User.Identity.IsAuthenticated || User.IsInRole("Cliente"))
                    {
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="sidebar-layout">

        @if (User.Identity.IsAuthenticated)
        {
            <div class="sidebar-aside-content">
                <!-- Content of sidebar -->
                <ul class="sidebar-nav">
                    @if (User.IsInRole("Superadministrador"))
                    {
                        <li>
                            <a href="@Url.Action("Index", "Administrador")">
                                <i class="zmdi zmdi-accounts"></i> Administradores
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "SistemaExterno")">
                                <i class="zmdi zmdi-rss"></i> Sistemas Externos
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Administrador"))
                    {
                        <li>
                            <a href="@Url.Action("Index", "Administrador")">
                                <i class="zmdi zmdi-accounts"></i> Administradores
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Funcionario")">
                                <i class="zmdi zmdi-accounts"></i> Funcionarios
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Agencia")">
                                <i class="zmdi zmdi-home"></i> Agencias
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Trayecto")">
                                <i class="zmdi zmdi-navigation"></i> Trayectos
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "PermisosDeUsuarios")">
                                <i class="zmdi zmdi-shield-security"></i> Permisos
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "ReportesGraficos")">
                                <i class="zmdi zmdi-chart"></i> Reportes Gráficos
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Funcionario"))
                    {
                        <li>
                            <a href="@Url.Action("Index", "Cliente")">
                                <i class="zmdi zmdi-accounts"></i> Clientes
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Paquete")">
                                <i class="zmdi zmdi-mall"></i> Paquetes
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "ReportePaquetes")">
                                <i class="zmdi zmdi-search"></i> Filtro paquetes
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "ReportesGraficos")">
                                <i class="zmdi zmdi-chart"></i> Reportes Gráficos
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Cliente"))
                    {
                        <li>
                            <a href="@Url.Action("Index", "PaquetesEnviados")">
                                <i class="zmdi zmdi-mail-send"></i> Paquetes Enviados
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "PaquetesRecibidos")">
                                <i class="zmdi zmdi-mail-reply"></i> Paquetes Recibidos
                            </a>
                        </li>
                    }
                </ul>
            </div>
        }

        <div class="container body-content sidebar-body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - TrackingFULL</p>
            </footer>
        </div>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>